# Render config for the Picksies project
services:
- type: web
  name: Picksies
  plan: free
  envVars:
  - key: BUN_VERSION
    value: "1.2.3"
    sync: false
  - key: CLERK_SIGNING_SECRET
    sync: false
  - key: NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY
    sync: false
  - key: CLERK_SECRET_KEY
    sync: false
  - key: DATABASE_URL
    sync: false
  - key: PORT
    value: "3004"
    sync: false
  region: oregon
  buildCommand: pnpm install --frozen-lockfile
  startCommand: pnpm start
  healthCheckPath: /health
  rootDir: apps/api
version: "1"
